const hotels = [
  {
    description:
      "Celestino Boutique Hotel is located in Medellín, 1 street away from Parque Lleras, and offers free WiFi.",
    image:
      "https://hotelcelestino.com/wp-content/uploads/2023/10/a05081_5bb94a6dd4994b58b7ff425cca3a0882mv2.jpg",
    location: "Hotel in El Poblado, Medellín",
    name: "Celestino Boutique Hotel",
    price: "441600",
    rating: "8.8",
    review: "Fabulous",
    reviewCount: "2091",
    roomtypes: [
      {
        type: "Single Room",
        price: 441600,
        maxguests: 1,
        rooms: [
          { id: "01S", available: false },
          { id: "02S", available: true },
          {
            id: "03S",
            available: true,
          },
          { id: "04S", available: true },
          { id: "05S", available: true },
          { id: "06S", available: true },
          {
            id: "07S",
            available: true,
          },
          { id: "08S", available: true },
          { id: "09S", available: true },
          { id: "10S", available: true },
        ],
      },
      {
        type: "Double Room",
        price: 521600,
        maxguests: 2,
        rooms: [
          { id: "11D", available: false },
          { id: "12D", available: true },
          {
            id: "13D",
            available: true,
          },
          { id: "14D", available: true },
          { id: "15D", available: true },
          { id: "16D", available: true },
          {
            id: "17D",
            available: true,
          },
          { id: "18D", available: true },
          { id: "19D", available: true },
          { id: "20D", available: true },
        ],
      },
      {
        type: "Family Suite",
        price: 661600,
        maxguests: 4,
        rooms: [
          { id: "21F", available: false },
          { id: "22F", available: false },
          {
            id: "23F",
            available: true,
          },
          { id: "24F", available: true },
          { id: "25F", available: true },
          { id: "26F", available: true },
          {
            id: "27F",
            available: true,
          },
          { id: "28F", available: true },
          { id: "29F", available: true },
          { id: "30F", available: true },
        ],
      },
      {
        type: "Executive Studio",
        price: 701600,
        maxguests: 2,
        rooms: [
          { id: "31E", available: true },
          { id: "32E", available: true },
          {
            id: "33E",
            available: true,
          },
          { id: "34E", available: true },
          { id: "35E", available: true },
          { id: "36E", available: true },
          {
            id: "37E",
            available: true,
          },
          { id: "38E", available: true },
          { id: "39E", available: true },
          { id: "40E", available: true },
        ],
      },
      {
        type: "Luxury Suite",
        price: 941600,
        maxguests: 4,
        rooms: [
          { id: "41L", available: false },
          { id: "42L", available: true },
          {
            id: "43L",
            available: true,
          },
          { id: "44L", available: true },
          { id: "45L", available: true },
          { id: "46L", available: true },
          {
            id: "47L",
            available: true,
          },
          { id: "48L", available: true },
          { id: "49L", available: true },
          { id: "50L", available: true },
        ],
      },
    ],
  },
  {
    description:
      "HOTEL CAVALTA, which has a restaurant and bar, is located in Medellín, 5.2 km from Parque El Poblado and 5.9 km from Parque Lleras.",
    image: "https://cdn.precioyviajes.com/04/76/54/04765475_gp.jpeg",
    location: "Hotel in Laureles, Medellín",
    name: "Hotel Cavalta",
    price: "375000",
    rating: "8.4",
    review: "Very good",
    reviewCount: "3069",
    roomtypes: [
      {
        type: "Single Room",
        price: 375000,
        maxguests: 1,
        rooms: [
          { id: "51S", available: true },
          { id: "52S", available: true },
          {
            id: "53S",
            available: true,
          },
          { id: "54S", available: true },
          { id: "55S", available: true },
          { id: "56S", available: true },
          {
            id: "57S",
            available: true,
          },
          { id: "58S", available: true },
          { id: "59S", available: true },
          { id: "60S", available: true },
        ],
      },
      {
        type: "Double Room",
        price: 445000,
        maxguests: 2,
        rooms: [
          { id: "61D", available: true },
          { id: "62D", available: true },
          {
            id: "63D",
            available: true,
          },
          { id: "64D", available: true },
          { id: "65D", available: true },
          { id: "66D", available: true },
          {
            id: "67D",
            available: true,
          },
          { id: "68D", available: true },
          { id: "69D", available: true },
          { id: "70D", available: true },
        ],
      },
      {
        type: "Family Suite",
        price: 575000,
        maxguests: 4,
        rooms: [
          { id: "71F", available: true },
          { id: "72F", available: true },
          {
            id: "73F",
            available: true,
          },
          { id: "74F", available: true },
          { id: "75F", available: true },
          { id: "76F", available: true },
          {
            id: "77F",
            available: true,
          },
          { id: "78F", available: true },
          { id: "79F", available: true },
          { id: "80F", available: true },
        ],
      },
      {
        type: "Executive Studio",
        price: 615000,
        maxguests: 2,
        rooms: [
          { id: "81E", available: true },
          { id: "82E", available: true },
          {
            id: "83E",
            available: true,
          },
          { id: "84E", available: true },
          { id: "85E", available: true },
          { id: "86E", available: true },
          {
            id: "87E",
            available: true,
          },
          { id: "88E", available: true },
          { id: "89E", available: true },
          { id: "90E", available: true },
        ],
      },
      {
        type: "Luxury Suite",
        price: 815000,
        maxguests: 4,
        rooms: [
          { id: "91L", available: true },
          { id: "92L", available: true },
          {
            id: "93L",
            available: true,
          },
          { id: "94L", available: true },
          { id: "95L", available: true },
          { id: "96L", available: true },
          {
            id: "97L",
            available: true,
          },
          { id: "98L", available: true },
          { id: "99L", available: true },
          { id: "100L", available: true },
        ],
      },
    ],
  },
  {
    description:
      "Hotel Dann Carlton Belfort Medellín is located in a residential area 15 blocks from El Poblado metro station and 2.7 km from Pies Descalzos Park. Car rental service can be arranged.",
    image:
      "https://cf.bstatic.com/xdata/images/hotel/max500/105359365.jpg?k:fd1b6893812f1b8d0d7297736cdf6c3557d6757ff52aca08f8fa61d08468d7ea&o:&hp:1",
    location: "Hotel in El Poblado, Medellín",
    name: "Hotel Dann Carlton Belfort Medellin",
    price: "398000",
    rating: "8.6",
    review: "Fabulous",
    reviewCount: "4712",
    roomtypes: [
      {
        type: "Single Room",
        price: 398000,
        maxguests: 1,
        rooms: [
          { id: "101S", available: true },
          { id: "102S", available: true },
          {
            id: "103S",
            available: true,
          },
          { id: "104S", available: true },
          { id: "105S", available: true },
          { id: "106S", available: true },
          {
            id: "107S",
            available: true,
          },
          { id: "108S", available: true },
          { id: "109S", available: true },
          { id: "110S", available: true },
        ],
      },
      {
        type: "Double Room",
        price: 478000,
        maxguests: 2,
        rooms: [
          { id: "111D", available: true },
          { id: "112D", available: true },
          {
            id: "113D",
            available: true,
          },
          { id: "114D", available: true },
          { id: "115D", available: true },
          { id: "116D", available: true },
          {
            id: "117D",
            available: true,
          },
          { id: "118D", available: true },
          { id: "119D", available: true },
          { id: "120D", available: true },
        ],
      },
      {
        type: "Family Suite",
        price: 618000,
        maxguests: 4,
        rooms: [
          { id: "121F", available: true },
          { id: "122F", available: true },
          {
            id: "123F",
            available: true,
          },
          { id: "124F", available: true },
          { id: "125F", available: true },
          { id: "126F", available: true },
          {
            id: "127F",
            available: true,
          },
          { id: "128F", available: true },
          { id: "129F", available: true },
          { id: "130F", available: true },
        ],
      },
      {
        type: "Executive Studio",
        price: 658000,
        maxguests: 2,
        rooms: [
          { id: "131E", available: true },
          { id: "132E", available: true },
          {
            id: "133E",
            available: true,
          },
          { id: "134E", available: true },
          { id: "135E", available: true },
          { id: "136E", available: true },
          {
            id: "137E",
            available: true,
          },
          { id: "138E", available: true },
          { id: "139E", available: true },
          { id: "140E", available: true },
        ],
      },
      {
        type: "Luxury Suite",
        price: 878000,
        maxguests: 4,
        rooms: [
          { id: "141L", available: true },
          { id: "142L", available: true },
          {
            id: "143L",
            available: true,
          },
          { id: "144L", available: true },
          { id: "145L", available: true },
          { id: "146L", available: true },
          {
            id: "147L",
            available: true,
          },
          { id: "148L", available: true },
          { id: "149L", available: true },
          { id: "150L", available: true },
        ],
      },
    ],
  },
  {
    _id: { $oid: "6654e9fd0356fb5de30b94db" },
    description:
      "Hotel York Luxury Suites Medellin by Preferred is located in Medellín and offers accommodation, restaurant, fitness center, outdoor pool, and free private parking. It also has a bar and common lounge. It is 2.9 km from El Poblado Park and 8 km from Pueblito Paisa. There is a 24-hour reception, room service, free WiFi, and airport shuttle service.",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/09/fe/7c/bluedoors-york-suite.jpg?w:1100&h:-1&s:1",
    location: "Hotel in El Poblado, Medellín",
    name: "Hotel York Luxury Suites Medellin",
    price: "617760",
    rating: "9.1",
    review: "Fantastic",
    reviewCount: "1233",
    roomtypes: [
      {
        type: "Single Room",
        price: 617760,
        maxguests: 1,
        rooms: [
          { id: "151S", available: true },
          { id: "152S", available: true },
          {
            id: "153S",
            available: true,
          },
          { id: "154S", available: true },
          { id: "155S", available: true },
          { id: "156S", available: true },
          {
            id: "157S",
            available: true,
          },
          { id: "158S", available: true },
          { id: "159S", available: true },
          { id: "160S", available: true },
        ],
      },
      {
        type: "Double Room",
        price: 697760,
        maxguests: 2,
        rooms: [
          { id: "161D", available: true },
          { id: "162D", available: true },
          {
            id: "163D",
            available: true,
          },
          { id: "164D", available: true },
          { id: "165D", available: true },
          { id: "166D", available: true },
          {
            id: "167D",
            available: true,
          },
          { id: "168D", available: true },
          { id: "169D", available: true },
          { id: "170D", available: true },
        ],
      },
      {
        type: "Family Suite",
        price: 837760,
        maxguests: 4,
        rooms: [
          { id: "171F", available: true },
          { id: "172F", available: true },
          {
            id: "173F",
            available: true,
          },
          { id: "174F", available: true },
          { id: "175F", available: true },
          { id: "176F", available: true },
          {
            id: "177F",
            available: true,
          },
          { id: "178F", available: true },
          { id: "179F", available: true },
          { id: "180F", available: true },
        ],
      },
      {
        type: "Executive Studio",
        price: 877760,
        maxguests: 2,
        rooms: [
          { id: "181E", available: true },
          { id: "182E", available: true },
          {
            id: "183E",
            available: true,
          },
          { id: "184E", available: true },
          { id: "185E", available: true },
          { id: "186E", available: true },
          {
            id: "187E",
            available: true,
          },
          { id: "188E", available: true },
          { id: "189E", available: true },
          { id: "190E", available: true },
        ],
      },
      {
        type: "Luxury Suite",
        price: 1117760,
        maxguests: 4,
        rooms: [
          { id: "191L", available: true },
          { id: "192L", available: true },
          {
            id: "193L",
            available: true,
          },
          { id: "194L", available: true },
          { id: "195L", available: true },
          { id: "196L", available: true },
          {
            id: "197L",
            available: true,
          },
          { id: "198L", available: true },
          { id: "199L", available: true },
          { id: "200L", available: true },
        ],
      },
    ],
  },
  {
    description:
      "Estelar La Torre Suites is located in Medellín, 1 street away from Parque Lleras, and offers free WiFi.",
    image:
      "https://estelar-la-torre-suites.medellin-hotels.com/data/Photos/OriginalPhoto/12838/1283885/1283885608.JPEG",
    location: "Hotel in El Poblado, Medellín",
    name: "Estelar La Torre Suites",
    price: "495000",
    rating: "9.3",
    review: "Fantastic",
    reviewCount: "193",
    roomtypes: [
      {
        type: "Single Room",
        price: 495000,
        maxguests: 1,
        rooms: [
          { id: "201S", available: true },
          { id: "202S", available: true },
          {
            id: "203S",
            available: true,
          },
          { id: "204S", available: true },
          { id: "205S", available: true },
          { id: "206S", available: true },
          {
            id: "207S",
            available: true,
          },
          { id: "208S", available: true },
          { id: "209S", available: true },
          { id: "210S", available: true },
        ],
      },
      {
        type: "Double Room",
        price: 575000,
        maxguests: 2,
        rooms: [
          { id: "211D", available: true },
          { id: "212D", available: true },
          {
            id: "213D",
            available: true,
          },
          { id: "214D", available: true },
          { id: "215D", available: true },
          { id: "216D", available: true },
          {
            id: "217D",
            available: true,
          },
          { id: "218D", available: true },
          { id: "219D", available: true },
          { id: "220D", available: true },
        ],
      },
      {
        type: "Family Suite",
        price: 715000,
        maxguests: 4,
        rooms: [
          { id: "221F", available: true },
          { id: "222F", available: true },
          {
            id: "223F",
            available: true,
          },
          { id: "224F", available: true },
          { id: "225F", available: true },
          { id: "226F", available: true },
          {
            id: "227F",
            available: true,
          },
          { id: "228F", available: true },
          { id: "229F", available: true },
          { id: "230F", available: true },
        ],
      },
      {
        type: "Executive Studio",
        price: 755000,
        maxguests: 2,
        rooms: [
          { id: "231E", available: true },
          { id: "232E", available: true },
          {
            id: "233E",
            available: true,
          },
          { id: "234E", available: true },
          { id: "235E", available: true },
          { id: "236E", available: true },
          {
            id: "237E",
            available: true,
          },
          { id: "238E", available: true },
          { id: "239E", available: true },
          { id: "240E", available: true },
        ],
      },
      {
        type: "Luxury Suite",
        price: 995000,
        maxguests: 4,
        rooms: [
          { id: "241L", available: true },
          { id: "242L", available: true },
          {
            id: "243L",
            available: true,
          },
          { id: "244L", available: true },
          { id: "245L", available: true },
          { id: "246L", available: true },
          {
            id: "247L",
            available: true,
          },
          { id: "248L", available: true },
          { id: "249L", available: true },
          { id: "250L", available: true },
        ],
      },
    ],
  },
];
